name: SIMS Primary Online Help

markdown: kramdown

collections:
  docs:
    output: true
  glossary:
    output: false
  broadcast:
    output: true
  images:
    output: true

defaults:
- scope:
    path: ""
    type: docs
  values:
    layout: docs